### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by Asuanin** [PatrikValkovic/csfd-api#5]
> TypeError: Cannot read property 'trim' of undefined
    at Object.elements.map (/home/mediaserver/Dokumenty/Projects/CSFD to nfo nodejs/node_modules/csfd-api/lib/parsers/filmParser.js:51:25)
    at /home/mediaserver/Dokumenty/Projects/CSFD to nfo nodejs/node_modules/cheerio/lib/api/traversing.js:274:18
    at Function.reduce (/home/mediaserver/Dokumenty/Projects/CSFD to nfo nodejs/node_modules/lodash/dist/lodash.js:3735:25)
    at module.exports.exports.map (/home/mediaserver/Dokumenty/Projects/CSFD to nfo nodejs/node_modules/cheerio/lib/api/traversing.js:273:23)
    at parseNames (/home/mediaserver/Dokumenty/Projects/CSFD to nfo nodejs/node_modules/csfd-api/lib/parsers/filmParser.js:45:19)
    at Object.module.exports [as film] (/home/mediaserver/Dokumenty/Projects/CSFD to nfo nodejs/node_modules/csfd-api/lib/parsers/filmParser.js:191:13)
    at Object.csfd.film (/home/mediaserver/Dokumenty/Projects/CSFD to nfo nodejs/node_modules/csfd-api/lib/csfd.js:36:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Verze: 1.1.3
CSFD ID: 300893

Pravděpodobně je to způsobeno položkou "(další názvy)" v listu názvů jazyků

**Comment by Asuanin** [comment]
Edit: je tam prázdný <li>

**Comment by PatrikValkovic** [comment]
Jsem si toho vědom, ze včerejška na dnešek začali selhávat buildy a zřejmě změnili strukturu webu. Podívám se na to co nejdřív.

**Comment by Asuanin** [comment]
OK zatím jsem si to u sebe fixnul takto :)

filmParser.js:46
`if ($(element).text().trim() === '') {
  return;
}`
