### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by janodvarko** [PatrikValkovic/csfd-api#6]
It looks like `parseLength` method (in filmParser.js) doesn't work properly and fails on unexpected time format.

I am seeing an exception on this line:
https://github.com/PatrikValkovic/csfd-api/blob/master/lib/parsers/filmParser.js#L90

```
TypeError: Cannot read property 'replace' of undefined
    at parseLength (C:\src\bitbucket.org\janodvarko\movie-lib\server\node_modules\csfd-api\lib\parsers\filmParser.js:90:37)
    at Object.module.exports [as film] (C:\src\bitbucket.org\janodvarko\movie-lib\server\node_modules\csfd-api\lib\parsers\filmParser.js:208:3)
    at Object.csfd.film (C:\src\bitbucket.org\janodvarko\movie-lib\server\node_modules\csfd-api\lib\csfd.js:37:18)
```

Happens when calling the following API: `await csfd.film(691446);`

For this film:
https://www.csfd.cz/film/691446-velke-dobrodruzstvi-ctyrlistku/prehled/

Looks like the time format is unexpected:

`Česko, 2019, 72 min (Televizní verze: 4x15 min)`

`justTime` is set to `verze:` but it should rather be set to something like `4x15`

HTH

Honza

**Comment by PatrikValkovic** [comment]
Fix in version `v1.1.5`.
